apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels: { app: mysql }
  replicas: 1
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: master
          image: mysql:8
          imagePullPolicy: IfNotPresent
          resources: { requests: { cpu: 50m, memory: 100Mi } }
          ports:
            - { name: mysql, containerPort: 3306 }
          env:
            - { name: TZ, value: UTC }
            - { name: MYSQL_USER, value: alterboy }
            - { name: MYSQL_DATABASE, value: alterboy }
            - { name: MYSQL_PASSWORD, value: somethingMadeUpForDevelopment }
            - {
                name: MYSQL_ROOT_PASSWORD,
                value: somethingMadeUpForDevelopment,
              }
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels: { app: mysql }
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector: { app: mysql }
